# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oikp9jGEjC2D17yq699FdDO3xr8lTKQM
"""

!pip install gradio

import cv2
import numpy as np
import gradio as gr
from PIL import Image, ImageDraw

# Image Processor
def process_image_multiclass(input_image):
    image = cv2.cvtColor(np.array(input_image), cv2.COLOR_RGB2BGR)
    original = image.copy()
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Red - Plantation Needed
    lower_barren = np.array([0, 0, 0])
    upper_barren = np.array([179, 60, 180])
    barren_mask = cv2.inRange(hsv, lower_barren, upper_barren)
    r, g, b = cv2.split(rgb)
    dry_soil_mask = (g < 90) & (r > 100) & (b > 70)
    dry_soil_mask = dry_soil_mask.astype(np.uint8) * 255
    red_mask = cv2.bitwise_or(barren_mask, dry_soil_mask)

    # Green - Balanced Vegetation
    lower_balanced = np.array([35, 60, 60])
    upper_balanced = np.array([85, 255, 255])
    green_mask = cv2.inRange(hsv, lower_balanced, upper_balanced)

    # Blue - Overgrown Vegetation
    lower_overgrown = np.array([35, 100, 100])
    upper_overgrown = np.array([85, 255, 255])
    overgrown_mask = cv2.inRange(hsv, lower_overgrown, upper_overgrown)

    # Contours
    output = original.copy()
    cv2.drawContours(output, cv2.findContours(red_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)[0], -1, (0, 0, 255), 2)
    cv2.drawContours(output, cv2.findContours(green_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)[0], -1, (0, 255, 0), 2)
    cv2.drawContours(output, cv2.findContours(overgrown_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)[0], -1, (255, 0, 0), 2)

    output_rgb = cv2.cvtColor(output, cv2.COLOR_BGR2RGB)
    return Image.fromarray(output_rgb)

# Distance Display on Click
def show_distance(processed_image_pil, evt: gr.SelectData):
    x, y = evt.index
    img_height = processed_image_pil.height
    distance = img_height - y

    # Annotate clicked point
    image = processed_image_pil.copy()
    draw = ImageDraw.Draw(image)
    draw.ellipse((x - 5, y - 5, x + 5, y + 5), fill=(255, 255, 0))
    draw.text((x + 10, y), f"{distance}px", fill=(255, 255, 0))

    return image, f"Distance from bottom: {distance} pixels"

# Gradio Interface
with gr.Blocks() as demo:
    gr.Markdown("Upload an image and click on any point to see distance from the bottom.")

    with gr.Row():
        image_input = gr.Image(type="pil", label="Upload Image")
        image_output = gr.Image(type="pil", label="Processed Image (Click to Measure Distance)")

    distance_display = gr.Textbox(label="Distance Output")

    image_input.upload(fn=process_image_multiclass, inputs=image_input, outputs=image_output)
    image_output.select(fn=show_distance, inputs=image_output, outputs=[image_output, distance_display])

demo.launch()

from google.colab import drive
drive.mount('/content/drive')